drivers: soc: qtee_shmbridge: add missing missing MODULE_LICENSE
add missing MODULE_LICENSE which was reported below failure during
 module build

ERROR: modpost: missing MODULE_LICENSE() in drivers/soc/qcom/qtee_shmbridge.o

Reported-by: Bhupesh Sharma <bhupesh.sharma@linaro.org>
Signed-off-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>